name: boolean_selector
version: 2.1.0-nullsafety
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
homepage: https://github.com/dart-lang/boolean_selector

environment:
  sdk: '>=2.9.0-18.0 <2.9.0'

dependencies:
  source_span: '>=1.8.0-nullsafety <1.8.0'
  string_scanner: '>=1.1.0-nullsafety <1.1.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: any
  test_api: any
  test_core: any

dependency_overrides:
  async:
    git:
      url: git://github.com/dart-lang/async.git
      ref: null_safety
  charcode:
    git:
      url: git://github.com/dart-lang/charcode.git
      ref: null_safety
  collection: 1.15.0-nullsafety
  js:
    git:
      url: git://github.com/dart-lang/sdk.git
      path: pkg/js
  matcher:
    git:
      url: git://github.com/dart-lang/matcher.git
      ref: null_safety
  meta: 1.3.0-nullsafety
  path:
    git:
      url: git://github.com/dart-lang/path.git
      ref: null_safety
  pedantic:
    git:
      url: git://github.com/dart-lang/pedantic.git
      ref: null_safety
  pool:
    git:
      url: git://github.com/dart-lang/pool.git
      ref: null_safety
  source_maps:
    git:
      url: git://github.com/dart-lang/source_maps.git
      ref: null_safety
  source_map_stack_trace:
    git:
      url: git://github.com/dart-lang/source_map_stack_trace.git
      ref: null_safety
  source_span:
    git:
      url: git://github.com/dart-lang/source_span.git
      ref: null_safety
  stack_trace:
    git:
      url: git://github.com/dart-lang/stack_trace.git
      ref: null_safety
  stream_channel:
    git:
      url: git://github.com/dart-lang/stream_channel.git
      ref: null_safety
  string_scanner:
    git:
      url: git://github.com/dart-lang/string_scanner.git
      ref: null_safety
  term_glyph:
    git:
      url: git://github.com/dart-lang/term_glyph.git
      ref: null_safety
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test
