name: boolean_selector
version: 2.0.0
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
homepage: https://github.com/dart-lang/boolean_selector

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  source_span: ^1.0.0
  string_scanner: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.2.0

dependency_overrides:
  test: 1.11.1
  test_api: 0.2.13
  test_core: 0.2.18
